Areas/Admin/Controllers/FileManagerController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using shunshine.App.ApplicationServices.ServiceInterfaces;
using shunshine.App.Models.ViewModels;
using shunshine.App.Utilities.Dtos;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http.Headers;

namespace shunshine.Areas.Admin.Controllers
{
    public class FileManagerController : BaseController
    {
        private readonly IImageServiceInterface _imageServiceInterface;

        private readonly IHostingEnvironment _hostingEnvironment;

        public FileManagerController(IImageServiceInterface imageServiceInterface, IHostingEnvironment hostingEnvironment)
        {
            _imageServiceInterface = imageServiceInterface;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllFolder()
        {
            try
            {
                string pathRootFolder = HttpContext.Request.Query["folderRoot"].ToString();

                string pathRoot = Directory.GetCurrentDirectory().ToString() + "/" + pathRootFolder;
                var listFolder = Directory.GetDirectories(pathRoot);

                List<string> folderResult = new List<string>();

                foreach (var folder in listFolder)
                {
                    folderResult.Add(DirectoryFileManager.ReplacePathFolder(pathRoot, folder));
                }

                return new OkObjectResult(folderResult);
            }
            catch (Exception e)
            {
                return new OkObjectResult(e.Message.ToString());
            }
        }

        [HttpGet]
        public IActionResult GetListFile()
        {
            try
            {
                string pathFolder = HttpContext.Request.Query["pathFolder"].ToString();

                string path = Directory.GetCurrentDirectory().ToString() + "/" + pathFolder;

                var listFile = Directory.GetFiles(path);

                return new OkObjectResult(listFile);
            }
            catch (Exception e)
            {
                return new OkObjectResult(e.Message.ToString());
            }
        }

        [HttpPost]
        public IActionResult UploadImage()
        {
            try
            {
                var baseRootUrl = HttpContext.Request.Scheme + "://" + HttpContext.Request.Host;

                string webRootPath = _hostingEnvironment.WebRootPath;
                string contentRootPath = _hostingEnvironment.ContentRootPath;

                var files = HttpContext.Request.Form.Files;

                string yearCurrent = DateTime.Now.Year.ToString();

                string monthCurrent = DateTime.Now.Month.ToString();

                List<ImageViewModel> Images = new List<ImageViewModel>();

                foreach (var file in files)
                {
                    string timeCurrent = DateTime.Now.ToString("yyyyMMddHHmmssffff");

                    string fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                    fileName = timeCurrent + fileName;

                    string imageFolder = $@"\uploaded\images\{yearCurrent}\{monthCurrent}";

                    string folder = _hostingEnvironment.WebRootPath + imageFolder;

                    if (!Directory.Exists(folder))
                    {
                        Directory.CreateDirectory(folder);
                    }
                    string filePath = Path.Combine(folder, fileName);

                    using (FileStream fileStream = System.IO.File.Create(filePath))
                    {
                        file.CopyTo(fileStream);
                        fileStream.Flush();
                    }

                    ImageViewModel imageViewModel = new ImageViewModel();

                    imageViewModel.Year = int.Parse(yearCurrent);
                    imageViewModel.Month = int.Parse(monthCurrent);
                    imageViewModel.Name = fileName;
                    imageViewModel.Url = baseRootUrl + imageFolder.Replace("\\", "/") + "/" + fileName;
                    imageViewModel.Size = int.Parse(file.Length.ToString());
                    imageViewModel.Type = file.ContentType;
                    imageViewModel.Extension = Path.GetExtension(fileName);

                    Images.Add(imageViewModel);
                }

                _imageServiceInterface.InsertMuilty(Images);
                _imageServiceInterface.SaveChanges();

                return new OkObjectResult(new GenericResult(true, "Upload success"));
            }
            catch (Exception exception)
            {
                return new OkObjectResult(new GenericResult(false, exception.Message.ToString()));
            }
        }

        [HttpGet]
        public IActionResult GetListYeas()
        {
            var years = _imageServiceInterface.GetListYear();

            return new OkObjectResult(years);
        }

        public IActionResult GetListMonths()
        {
            int year = int.Parse(HttpContext.Request.Query["year"].ToString());

            var months = _imageServiceInterface.GetListMonth(year);

            return new OkObjectResult(months);
        }

        public IActionResult GetListImage()
        {
            string year = HttpContext.Request.Query["year"];

            string month = HttpContext.Request.Query["month"];

            var images = _imageServiceInterface.GetAll(year, month);

            return new OkObjectResult(images);
        }

        public IActionResult getListPaginageImage()
        {
            int pageCurrent = int.Parse(HttpContext.Request.Query["pageCurrent"]);

            int pageSize = int.Parse(HttpContext.Request.Query["pageSize"]);

            string keyword = HttpContext.Request.Query["keyword"];

            var results = _imageServiceInterface.GetAll(pageCurrent, pageSize, keyword);

            return new OkObjectResult(results);
        }

        public PartialViewResult GetFileManagerPartial()
        {
            return PartialView("Index");
        }
    }
}

Areas/Admin/Views/Shared/FileManager/_Upload.cshtml
<div class="modal fade" id="fileManager" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <span class="modal-title text-center" id="exampleModalLongTitle"><strong>File Manager Shunshine</strong></span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <button class="btn btn-success" id="btnSwichFileList">Files list</button>
                            <button class="btn btn-dark" id="btnSwichUpload">Upload</button>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-primary">Go!</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="contentListFile">
                        <div class="col-sm-2 col-md-2" style="min-height: 300px; background: aliceblue; border-radius: 5px">
                            <ul class="menu-muilty" id="fm-sidebar">
                                <li class="shunshine-active active-change"><i class="fa fa-folder" aria-hidden="true"></i> All</li>
                                <li class="active-change"><i class="fa fa-folder" aria-hidden="true"></i> File</li>
                                <li class="active-change">
                                    <i class="fa fa-folder" aria-hidden="true"></i> Image
                                    <div id="fileManagerSideberContent"></div>

                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-10 col-md-10">
                            <div class="container-fluid">
                                <div class="row" id="rowConentImageList">
                                    <div class="col-xs-4 col-sm-3 col-md-2 nopad text-center">
                                        <label class="image-checkbox">
                                            <img class="img-responsive" src="https://dummyimage.com/600x400/000/fff" />
                                            <input type="checkbox" name="image[]" value="" />
                                            <i class="fa fa-check hidden"></i>
                                        </label>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row" id="contentFileUpload" style="display: none">

                        <div class="container-fluid" id="shunshine-drop">
                            <div id="actions" class="row">
                                <div class="col-lg-7">
                                    <!-- The fileinput-button span is used to style the file input field as button -->
                                    <span class="btn btn-success fileinput-button " id="btnAddUpload">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        <span>Add files...</span>

                                    </span>
                                    <button type="submit" id="btnStartUpload" class="btn btn-primary start">
                                        <i class="glyphicon glyphicon-upload"></i>
                                        <span>Start upload</span>
                                    </button>
                                </div>
                                <input type="file" class="hidden" id="txtAddUpload" name="txtAddUpload" multiple />
                            </div>
                            <div class="clearfix"></div>

                            <div class="row" style="height: 200px; width:100%; border: 2px #21cbcb dotted">
                                <h3 class="text-center" style="line-height:200px" id="total-file-upload">0 files upload</h3>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button class="btn btn-secondary" id="btnChooseImage">Choose</button>
            </div>
        </div>
    </div>
</div>
<script src="~/app/shrared/file-manager/dropzone-custom.js"></script>
<script src="~/app/shrared/file-manager/index.js"></script>
<script>

    var fileManagerController = new FileManagerController(
        "@Url.Action("GetAllFolder", "FileManager", new { Area = "admin" })"
    );
    fileManagerController.Initial();

</script>