Areas/Admin/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using shunshine.App.ApplicationServices.ServiceInterfaces;
using shunshine.App.Models.ViewModels;
using shunshine.App.Utilities.Dtos;

namespace shunshine.Areas.Admin.Controllers
{
    public class ProductCategoryController : BaseController
    {
        private IProductCategoryServiceInterface _categoryService;

        public ProductCategoryController(IProductCategoryServiceInterface categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllCategoryTree()
        {
            List<ProductCategoryViewModel> productCatogory = await _categoryService.GetAll();

            List<Object> arrayResult = new List<Object>();

            foreach (var items in productCatogory.Where(x => string.IsNullOrEmpty(x.ParentId.ToString())))
            {
                arrayResult.Add( new { parent = items, chirld = productCatogory.Where(x => x.ParentId == items.Id) });
            }

            return new OkObjectResult(arrayResult);
        }

        public async Task<IActionResult> GetAllTable()
        {
            List<ProductCategoryViewModel> productCatogory = await _categoryService.GetAll();

            return new OkObjectResult(productCatogory);
        }

        [HttpGet]
        public IActionResult GetAllPaginate()
        {
            // KEYWORD Query String (GET data)
            //var values = Request.Query.ToList ()
            int pageCurrent = Int32.Parse(HttpContext.Request.Query["pageCurrent"].ToString());

            int pageSize = Int32.Parse(HttpContext.Request.Query["pageSize"].ToString());

            string keyword = HttpContext.Request.Query["keyword"].ToString();

            var lstCategory = _categoryService.GetAllPaginate (pageCurrent, pageSize, keyword);

            return new OkObjectResult(lstCategory);
        }

        public async Task<IActionResult> GetListParent()
        {
            List<ProductCategoryViewModel> parents = await _categoryService.GetAllParent();

            return new OkObjectResult(parents);
        }

        [HttpPost]
        public IActionResult SaveEntity(ProductCategoryViewModel productCategoryViewModel)
        {
  
            try
            {
                if (!ModelState.IsValid)
                {
                    IEnumerable<ModelError> modelErrors = ModelState.Values.SelectMany(x => x.Errors);

                    return new OkObjectResult(new GenericResult(false, new { modelErrors }));
                }
                else
                {
                    if (!string.IsNullOrEmpty(productCategoryViewModel.SeoAlias))
                    {            
                        productCategoryViewModel.SeoAlias = Helper.ToUnsignString(productCategoryViewModel.SeoAlias);
                    }

                    if (!_categoryService.IsUnique(productCategoryViewModel.SeoAlias))
                    {
                        return new OkObjectResult(new GenericResult(false, new { SeoAlias = "The slug must be unique" }));
                    }

                    if (productCategoryViewModel.Id == 0)
                    {
                        _categoryService.Create(productCategoryViewModel);
                    }
                    else
                    {
                        _categoryService.Update(productCategoryViewModel);
                    }
                    _categoryService.Save();
                }

                return new OkObjectResult( new GenericResult(true));
            }
            catch(Exception exception)
            {
                return new OkObjectResult(new GenericResult(false, new { Message = exception.Message.ToString() }));
            }
        }

        public IActionResult GetById(int Id)
        {
            try
            {
                ProductCategoryViewModel productCategoryViewModelParent = new ProductCategoryViewModel();

                var productCategoryViewModel = _categoryService.FindById(Id);

                if (!string.IsNullOrEmpty(productCategoryViewModel.ParentId.ToString()))
                {
                    productCategoryViewModelParent = _categoryService.FindById(int.Parse(productCategoryViewModel.ParentId.ToString()));
                }

                ViewBag.ParentName = productCategoryViewModelParent.Name;

                return PartialView("View", productCategoryViewModel);
            }
            catch(Exception exception)
            {
                return new OkObjectResult(new GenericResult(false, new { Data = exception.Message.ToString()}));
            }
        }

        [HttpPost]
        public IActionResult DeleteCategoryById(int Id)
        {
            try
            {
                _categoryService.DeleteById(Id);
                _categoryService.Save();

                return new OkObjectResult(new GenericResult(true));
            }
            catch(Exception exception)
            {
                return new OkObjectResult(new GenericResult(false, new { Data = exception.Message.ToString()}));
            }
        }
    }
}

Areas/Admin/Views/ProductCategory/Index.cshtml
@*@model List<ProductCategoryViewModel>*@
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <link href="~/admin/css/style-custom.css" rel="stylesheet" />
}

<div class="panel-content shunshine-page-content">
    <div class="panel-body container-fluid">
        <div class="row row-lg">
            <div class="col-xl-12">
                <!-- Example Tabs Solid -->
                <div class="example-wrap">
                    <div class="nav-tabs-horizontal" data-plugin="tabs">
                        <ul class="nav nav-tabs nav-tabs-solid" role="tablist">
                            <li class="nav-item" role="presentation"><a class="nav-link active" data-toggle="tab" href="#categoryList" aria-controls="exampleTabsSolidOne" role="tab">Category List</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" data-toggle="tab" href="#position" aria-controls="exampleTabsSolidTwo" role="tab">Position</a></li>
                            <li class="dropdown nav-item" role="presentation" style="display: none;">
                                <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#" aria-expanded="false">Dropdown </a>
                                <div class="dropdown-menu" role="menu">
                                    <a class="dropdown-item" data-toggle="tab" href="#exampleTabsSolidOne" aria-controls="categoryList" role="tab">Category List</a>
                                    <a class="dropdown-item" data-toggle="tab" href="#exampleTabsSolidTwo" aria-controls="position" role="tab">Position</a>
                                </div>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="categoryList" role="tabpanel">
                                <div class="row container-fluid">
                                    <div class="col-md-6">
                                        <button type="button" class="btn btn-outline btn-primary" id="btnCreate">
                                            <i class="icon wb-add-file" aria-hidden="true"></i>
                                            Create
                                        </button>
                                        <button type="button" class="btn btn-outline btn-danger" id="btnDelete">
                                            <i class="icon wb-trash" aria-hidden="true"></i>
                                            Delete
                                        </button>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="input-group">
                                                <input type="text" class="form-control" id="txtSearchCategory" placeholder="Search...">
                                                <span class="input-group-append">
                                                    <button type="submit" id="btnSearchCategory" class="btn btn-primary"><i class="icon wb-search" aria-hidden="true"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <select data-plugin="selectpicker" id="paginateShowLimit" class="form-control">
                                                <option value="10">10</option>
                                                <option value="20">20</option>
                                                <option value="50">50</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <table class="table table-hover" data-plugin="selectable" data-row-selectable="true">
                                    <thead>
                                        <tr>
                                            <th class="w-50">
                                                <span class="checkbox-custom checkbox-primary">
                                                    <input class="selectable-all" type="checkbox">
                                                    <label></label>
                                                </span>
                                            </th>
                                            <th>
                                                Id
                                            </th>
                                            <th>
                                                Name
                                            </th>
                                            <th class="hidden-sm-down">
                                                Slug
                                            </th>

                                            <th class="hidden-sm-down">
                                                Date Created
                                            </th>
                                            <th class="hidden-sm-down">
                                                Status
                                            </th>
                                            <th>
                                                Action
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbodyContent">
                                        <tr>
                                            <td>
                                                <span class="checkbox-custom checkbox-primary">
                                                    <input class="selectable-item" type="checkbox" id="row-619" value="619">
                                                    <label for="row-619"></label>
                                                </span>
                                            </td>
                                            <td>619</td>
                                            <td>The sun climbing plan</td>
                                            <td>
                                            </td>
                                            <td>
                                            </td>
                                            <td></td>
                                            <td class="text-nowrap">
                                                <button type="button" class="btn btn-sm btn-icon btn-flat btn-default" data-toggle="tooltip" data-original-title="View" aria-describedby="tooltip662061">
                                                    <i class="icon wb-eye" aria-hidden="true"></i>
                                                </button><button type="button" class="btn btn-sm btn-icon btn-flat btn-default" data-toggle="tooltip" data-original-title="Edit" aria-describedby="tooltip662061">
                                                    <i class="icon wb-wrench" aria-hidden="true"></i>
                                                </button>
                                                <button type="button" class="btn btn-sm btn-icon btn-flat btn-default" data-toggle="tooltip" data-original-title="Delete">
                                                    <i class="icon wb-close" aria-hidden="true"></i>
                                                </button>
                                            </td>
                                        </tr>

                                    </tbody>
                                </table>
                                <div class="row ">
                                    <div class="col-md-6">
                                        <em>show 10 -20 / 200</em>
                                    </div>
                                    <div class="col-md-6">
                                        <ul id="paginateCategory" class="float-right"> </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="position" role="tabpanel">
                                Ambigua huc ipsarum similique malis physicis splendide, miser philosophi tria finitum
                                errata hominum emolumento officii explicabo appellantur,
                                suscipiet inciderit spatio, quantumcumque disciplinae maluisti
                                putarent cogitemus. Voluerint adipiscendarum aristotele
                                invidi fructuosam.
                            </div>

                        </div>
                    </div>
                </div>
                <!-- End Example Tabs Solid -->
            </div>
        </div>
    </div>
</div>
<div id="fileManagerContent"></div>
<div id="modalShowCategoryDetail"></div>
@section Scripts{
    <script src="~/app/shrared/shunshine.js"></script>
    <script src="~/app/controllers/product_category/index.js"></script>
    <script>
        var prodcutCategoryController = new ProductCategoryController();
        prodcutCategoryController.Initial();


        $(document).on("click", "#btnCreate", function () {
            $("#modalCreateCategory").modal("show");
            $("#frmCategoryShowMessage").html("");

            $.ajax({
                type: "GET",
                url: "/admin/productcategory/GetListParent",
                success: function (response) {
                    var render = "";
                    render += "<option value=''>--- Choose Parent ---</option>";
                    $.each(response, function(key, value){
                        render += "<option value='"+value.Id+"'>"+value.Name+"</option>";
                    })

                    $("#txtParentId").html(render);
                },
                error: function (response) {
                    console.log(response);
                    shunshine.showMessageError("Error when loading parent cateogory")
                }
            })
        })

        $(document).on("click", ".btnChooseFileName", function (event) {
            event.preventDefault();

            $.ajax({
                type: "GET",
                url: "/admin/FileManager/GetFileManagerPartial",
                beforeSend: function (data) {
                    shunshine.startLoading();
                },
                success: function (data) {
                    $("#fileManagerContent").html(data);
                    shunshine.stopLoading();
                }
            })

            setTimeout(function () {
                $("#shunshineFileManager").modal("show");
            }, 1000);

        })

        $(document).on("click", "#btnChooseImage",function () {
            var srcImage = $("#shunshineFileManagerListImageContent").find(".isChecked").first().val();
            $("#shunshineFileManager").modal("hide");
            $("#txtImage").val(srcImage);
        })
    </script>

}
@await Html.PartialAsync("_Form.cshtml")
@*@await Html.PartialAsync("~/Areas/Admin/Views/Shared/FileManager/Index.cshtml")*@

Areas/Admin/Views/ProductCategory/Index1.cshtml
@*@model List<ProductCategoryViewModel>*@
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <link href="~/admin/dashboard/vendor/switchery/dist/switchery.min.css" rel="stylesheet" />
    <link rel="stylesheet/less" type="text/css" href="~/admin/css/admin-side/css/treeview-css.less">
    <link href="~/admin/css/custom.css" rel="stylesheet" />
}
<div class="page-title">
    <div class="title_left">
        <h3>List Product Category</h3>
    </div>


</div>
<div class="clearfix"></div>
<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#createCategory">Create</button>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#fileManager">Delete</button>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a href="#">Settings 1</a>
                        </li>
                        <li>
                            <a href="#">Settings 2</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-3 col-sm-4" id="categoryLeft">
            </div>
            <div class="col-md-9 col-sm-8">
                <div class="row">
                    <div class="col-sm-3 col-md-3">
                        <div class="title_left select-paginate">
                            <select class="form-control" style="width: 70px" id="pageSize">
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="50">50</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm=3 col-md-3">
                        <div class="title_left select-paginate">
                            <select class="form-control" style="width: 110px" id="slStatus">
                                <option>All</option>
                                <option>Active</option>
                                <option>DeActice</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="title_right">
                            <div class="form-group pull-right top_search">
                                <div class="input-group">
                                    <input type="text" id="txtSearch" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">Go!</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" name="checkAll" id="checkAll" value="run" />
                                </th>
                                <th class="column-title">Name </th>
                                <th class="column-title">Slug </th>
                                <th class="column-title">Status </th>
                                <th class="column-title">DateCreated </th>
                                <th class="column-title">Date Modified </th>
                                <th class="column-title no-link last">
                                    <span class="nobr">Action</span>
                                </th>

                            </tr>
                        </thead>
                        <tbody id="tblContent">
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="" id="pageInfo">

                            </div>

                        </div>
                        <div class="col-sm-6">
                            <div class="dataTables_paginate paging_simple_numbers" id="datatable-responsive_paginate">
                                <ul class="pagination" id="paginationContent">
                                </ul>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/admin/dashboard/vendor/switchery/dist/switchery.min.js"></script>
    <script src="~/app/shrared/shunshine.js"></script>
    <script src="~/app/shrared/paginate.js"></script>
    <script src="~/app/controllers/product_category/index.js"></script>
    <script>
        var prodcutCategoryController = new ProductCategoryController(
            "@Url.Action("GetAllCategoryTree", "ProductCategory", new { Area = "admin" })",
            "@Url.Action("GetAllPaginate", "ProductCategory", new { Area = "admin"})"
        );
        prodcutCategoryController.inital();

        //var uploadFile = new uploadDropZone();
        //uploadFile.Initial();
    </script>

}
@await Html.PartialAsync("_Form.cshtml")
@await Html.PartialAsync("~/Areas/Admin/Views/Shared/FileManager/Index.cshtml");

Areas/Admin/Views/ProductCategory/View.cshtml
@model ProductCategoryViewModel

<div class="modal fade" id="modalViewCategoryDetail" tabindex="-1" role="dialog" aria-labelledby="Category" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <span class="modal-title" id="Category" style="font-size:20px">Category Form Create</span>
                <button type="button" class="close modalClose" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fuild" style="padding: 0px 30px">
                    <table class="table table-hover toggle-circle footable footable-4 footable-filtering footable-filtering-right footable-paging footable-paging-center breakpoint breakpoint-sm">
                        <tr>
                            <th>Name</th>
                            <td>@Model.Name</td>
                        </tr>
                        <tr>
                            <th>Slug</th>
                            <td>@Model.SeoAlias</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>@Model.Description</td>
                        </tr>
                        <tr>
                            <th>Parent</th>
                            <td>@ViewBag.ParentName</td>
                        </tr>
                        <tr>
                            <th>Image</th>
                            <td>
                                <img src="@Model.Image" alt="@Model.Name" style="max-width: 300px" />
                            </td>
                        </tr>
                        <tr>
                            <th>SeoPageTitle</th>
                            <td>@Model.SeoPageTitle</td>
                        </tr>
                        <tr>
                            <th>SeoKeywords</th>
                            <td>@Model.SeoKeywords</td>
                        </tr>
                        <tr>
                            <th>SeoDescription</th>
                            <td>@Model.SeoDescription</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>
                                @if (@Model.Status == Status.Active) {
                                    <span class="badge badge-pill badge-success">Active</span>
                                }
                                else
                                {
                                    <span class="badge badge-warning">Block</span>
                                }
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary modalClose" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>